### ISSUE TITLE
Question about the beat tracking algorithm

### ISSUE THREAD

**Issue by sevagh** [shortstheory/realtime-beat-tracking#1]
Hello - the visualization looks good on my laptop, it responds well to tempo and beat changes.

Which beat tracking algorithm are you using in the code? Does it have a name?

**Comment by shortstheory** [comment]
Thank you! There is no name given to the beat tracking algorithm here, I believe it just detects a "beat" if the currently detected amplitude is 7% greater than the amplitude of the mean amplitude of the previous few seconds. Very crude, and unfortunately not very generalizable for many cases.
